name: "Dozzle"
version: "8.14.2"
slug: "dozzle"
description: "A simple, lightweight application that provides you with a web based interface to monitor your Docker container logs live."
url: "https://dozzle.dev"
arch:
  - armv7
  - aarch64
  - amd64
init: false
startup: services
ingress: true
ingress_port: 8080
ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: "Web interface"
options:
  remote_host: ""
  remote_user: ""
  remote_key: ""
  no_analytics: true
  enable_actions: false
  hostname: ""
  level: "info"
  auth_provider: "none"
  auth_header_user: ""
  auth_header_email: ""
  auth_header_name: ""
  filter: ""
schema:
  remote_host: "str?"
  remote_user: "str?"
  remote_key: "str?"
  no_analytics: "bool"
  enable_actions: "bool"
  hostname: "str?"
  level: "list(trace|debug|info|warn|error|fatal|panic)?"
  auth_provider: "list(none|simple|forward-proxy)?"
  auth_header_user: "str?"
  auth_header_email: "str?"
  auth_header_name: "str?"
  filter: "str?"
auth_api: false
hassio_api: true