name: "Dozzle"
version: "8.14.2"
slug: "dozzle"
description: "A simple, lightweight application that provides you with a web based interface to monitor your Docker container logs live."
url: "https://dozzle.dev"
arch:
  - armv7
  - aarch64
  - amd64
init: false
startup: services
ingress: true
ingress_port: 8080
ingress_stream: true
options:
  remote_host: ""
  no_analytics: true
  enable_actions: false
  hostname: ""
  level: "info"
  filter: ""
schema:
  remote_host: "str?"
  no_analytics: "bool"
  enable_actions: "bool"
  hostname: "str?"
  level: "list(debug|info)?"
  filter: "str?"
auth_api: false
hassio_api: true