name: Build and Publish Beszel Addon

on:
  schedule:
    # Check for updates daily at 02:00 UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
  push:
    paths:
      - 'beszel/**'
      - '.github/workflows/beszel.yml'

permissions:
  contents: write
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/addon-beszel

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      should-build: ${{ steps.version-check.outputs.should-build }}
      beszel-version: ${{ steps.version-check.outputs.beszel-version }}
      addon-version: ${{ steps.version-check.outputs.addon-version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Beszel version
        id: version-check
        run: |
          # Get latest Beszel release
          BESZEL_VERSION=$(curl -s https://api.github.com/repos/henrygd/beszel/releases/latest | jq -r '.tag_name' | sed 's/^v//')
          echo "Latest Beszel version: $BESZEL_VERSION"
          
          # Get current addon version from config.yaml
          CURRENT_VERSION=$(grep '^version:' beszel/config.yaml | cut -d'"' -f2 | tr -d ' ')
          echo "Current addon version: $CURRENT_VERSION"
          
          # Set outputs
          echo "beszel-version=$BESZEL_VERSION" >> $GITHUB_OUTPUT
          echo "addon-version=$BESZEL_VERSION" >> $GITHUB_OUTPUT
          
          # Check if we need to build (version changed or manual trigger)
          if [ "$BESZEL_VERSION" != "$CURRENT_VERSION" ] || [ "${{ github.event_name }}" = "workflow_dispatch" ] || [ "${{ github.event_name }}" = "push" ]; then
            echo "should-build=true" >> $GITHUB_OUTPUT
            echo "Version update needed or manual trigger"
          else
            echo "should-build=false" >> $GITHUB_OUTPUT
            echo "No version update needed"
          fi

  build:
    needs: check-version
    if: needs.check-version.outputs.should-build == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        arch: [aarch64, amd64, armv7]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Update addon version
        run: |
          sed -i 's/^version:.*/version: "${{ needs.check-version.outputs.addon-version }}"/' beszel/config.yaml
          sed -i 's/^version:.*/version: "${{ needs.check-version.outputs.addon-version }}"/' beszel/build.yaml

      - name: Log current versions
        run: |
          echo "Building Beszel addon with:"
          echo "  Config version: $(grep '^version:' beszel/config.yaml | cut -d':' -f2 | tr -d ' \"')"
          echo "  Build version: $(grep '^version:' beszel/build.yaml | cut -d':' -f2 | tr -d ' \"')"
          echo "  Target Beszel version: v${{ needs.check-version.outputs.beszel-version }}"

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            suffix=-${{ matrix.arch }}
          tags: |
            type=raw,value=latest
            type=raw,value=${{ needs.check-version.outputs.addon-version }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./beszel
          platforms: linux/${{ matrix.arch == 'armv7' && 'arm/v7' || matrix.arch == 'aarch64' && 'arm64' || matrix.arch }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILD_FROM=ghcr.io/hassio-addons/base:18.1.3
            BUILD_ARCH=${{ matrix.arch }}
            BUILD_VERSION=${{ needs.check-version.outputs.addon-version }}
            BESZEL_VERSION=${{ needs.check-version.outputs.beszel-version }}

  commit-version:
    needs: [check-version, build]
    if: needs.check-version.outputs.should-build == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update addon version
        run: |
          sed -i 's/^version:.*/version: "${{ needs.check-version.outputs.addon-version }}"/' beszel/config.yaml
          sed -i 's/^version:.*/version: "${{ needs.check-version.outputs.addon-version }}"/' beszel/build.yaml

      - name: Commit version update
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add beszel/config.yaml beszel/build.yaml
          git diff --staged --quiet || (git commit -m "Update Beszel addon to version ${{ needs.check-version.outputs.addon-version }}" && git push)

  cleanup-packages:
    needs: [check-version, build]
    if: needs.check-version.outputs.should-build == 'true'
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Cleanup old container versions
        run: |
          echo "Package cleanup will run after a few successful builds to avoid errors on first runs"
          echo "Current build completed successfully - packages are available in the repository"