name: Cleanup Old Packages

on:
  schedule:
    # Run weekly on Sundays at 3 AM UTC
    - cron: '0 3 * * 0'
  workflow_dispatch:

permissions:
  packages: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old addon-dozzle packages
        uses: actions/delete-package-versions@v4
        with:
          package-name: '${{ github.repository }}/addon-dozzle'
          package-type: 'container'
          min-versions-to-keep: 5
          delete-only-untagged-versions: 'true'
        continue-on-error: true

      - name: Cleanup summary
        run: |
          echo "Package cleanup completed"
          echo "Keeping the 5 most recent versions of each architecture"
          echo "Only untagged versions are eligible for deletion"