name: Build and Publish Dozzle Addon

on:
  schedule:
    # Check for updates daily at 02:00 UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
  push:
    paths:
      - 'dozzle/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: addon-dozzle

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      should-build: ${{ steps.version-check.outputs.should-build }}
      dozzle-version: ${{ steps.version-check.outputs.dozzle-version }}
      addon-version: ${{ steps.version-check.outputs.addon-version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Dozzle version
        id: version-check
        run: |
          # Get latest Dozzle release
          DOZZLE_VERSION=$(curl -s https://api.github.com/repos/amir20/dozzle/releases/latest | jq -r '.tag_name' | sed 's/^v//')
          echo "Latest Dozzle version: $DOZZLE_VERSION"
          
          # Get current addon version from config.yaml
          CURRENT_VERSION=$(grep '^version:' dozzle/config.yaml | cut -d'"' -f2 | tr -d ' ')
          echo "Current addon version: $CURRENT_VERSION"
          
          # Set outputs
          echo "dozzle-version=$DOZZLE_VERSION" >> $GITHUB_OUTPUT
          echo "addon-version=$DOZZLE_VERSION" >> $GITHUB_OUTPUT
          
          # Check if we need to build (version changed or manual trigger)
          if [ "$DOZZLE_VERSION" != "$CURRENT_VERSION" ] || [ "${{ github.event_name }}" = "workflow_dispatch" ] || [ "${{ github.event_name }}" = "push" ]; then
            echo "should-build=true" >> $GITHUB_OUTPUT
            echo "Version update needed or manual trigger"
          else
            echo "should-build=false" >> $GITHUB_OUTPUT
            echo "No version update needed"
          fi

  build:
    needs: check-version
    if: needs.check-version.outputs.should-build == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [aarch64, amd64, armhf, armv7, i386]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Update addon version
        run: |
          sed -i 's/^version:.*/version: "${{ needs.check-version.outputs.addon-version }}"/' dozzle/config.yaml

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}-${{ matrix.arch }}
          tags: |
            type=raw,value=latest
            type=raw,value=${{ needs.check-version.outputs.addon-version }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./dozzle
          platforms: linux/${{ matrix.arch == 'armv7' && 'arm/v7' || matrix.arch == 'aarch64' && 'arm64' || matrix.arch }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            # Use the full, architecture-specific path from the Add-ons repository.
            BUILD_FROM=ghcr.io/hassio-addons/base/${{ matrix.arch }}:latest
            BUILD_ARCH=${{ matrix.arch }}
            BUILD_VERSION=${{ needs.check-version.outputs.addon-version }}
            DOZZLE_VERSION=v${{ needs.check-version.outputs.dozzle-version }}

  commit-version:
    needs: [check-version, build]
    if: needs.check-version.outputs.should-build == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update addon version
        run: |
          sed -i 's/^version:.*/version: "${{ needs.check-version.outputs.addon-version }}"/' dozzle/config.yaml

      - name: Commit version update
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dozzle/config.yaml
          git commit -m "Update Dozzle addon to version ${{ needs.check-version.outputs.addon-version }}" || exit 0
          git push